services:
  - type: web
    name: email-scraper-playwright
    env: python
    plan: free
    branch: playwright
    buildCommand: "./build.sh"
    startCommand: "uvicorn app:app --host=0.0.0.0 --port=10000"
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: 0



