services:
  - type: web
    name: email-scraper
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "uvicorn email_scraper:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
